apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: app-ts-hpa
  namespace: apps
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-ts
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75

