apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-nestjs-volume
  namespace: apps
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      name: first-pv