services:

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    restart: always
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLED_FORM_LOGIN=true
      - SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - ./config/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    depends_on: 
      - loki
      - tempo
      - mimir
      - prometheus
    
  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: always
    ports:
      - 3100:3100
      - 7946
      - 9095
  
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki
        mkdir -p /data/loki-server
        minio server /data --console-address ':9001'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=loki
      - MINIO_ROOT_PASSWORD=++loki++
    # command: server ~ --address ':9000' --console-address ':9001'
    volumes: 
      - ./minio-data:/data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 15s
      timeout: 10s
      retries: 3

  # Example for running Minio CLI commands
  # bucket:
  #   image: minio/mc:latest
  #   container_name: bucket
  #   environment: 
  #     - MINIO_HOST=http://minio:9000
  #     - MINIO_ACCESS_KEY=loki
  #     - MINIO_SECRET_KEY=++loki++
  #   depends_on:
  #     minio:
  #       condition: service_healthy
  #   entrypoint: >
  #     /bin/sh -c "
  #       /usr/bin/mc alias set minio $$MINIO_HOST $$MINIO_ACCESS_KEY $$MINIO_SECRET_KEY
  #       /usr/bin/mc rm -r --force minio/loki;
  #       /usr/bin/mc mb minio/loki;
  #       /usr/bin/mc anonymous set public minio/loki;
  #       exit 0;
  #     "
   
  tempo: 
    image: grafana/tempo:latest
    container_name: tempo
    restart: always
    volumes:
      - ./config/tempo/tempo.yaml:/etc/tempo.yaml
    command: ["-config.file=/etc/tempo.yaml"]
    expose: 
    - 4317
    - 4318
    - 3200
  
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: always
    volumes:
      - /var/log:/var/log
    command: [ "-config.file=/etc/promtail/config.yml"]

  mimir:
    image: grafana/mimir:latest
    container_name: mimir
    restart: always
    ports:
    - 9009:9009
    - 9008:9008
    command: [ "-config.file=/etc/mimir.yaml" ]
    volumes:
      - ./config/mimir/mimir.yaml:/etc/mimir.yaml
  
  otel:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel
    restart: always
    ports:
      - 4317:4317 # grpc receiver
      - 4318:4318 # http receiver
      - 8888:8888 # prometheus collector
      - 8889:8889 # prometheus exporter
      - 1888:1888 #pprof
      - 13133:13133 # health check
      - 55679:55679 # zpages

    command: [ "--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./config/otel/otel.yaml:/etc/otelcol/config.yaml
    depends_on:
      - tempo
      - mimir
      - loki
      - prometheus


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command: ["--web.enable-remote-write-receiver", "--config.file=/etc/prometheus/prometheus.yaml"]
    depends_on:
      - loki
      - tempo
      - mimir
volumes:
  minio-data: