Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    
    MASTER_CPUS = 2
    MASTER_MEM = 2048

    WORKER_CPUS = 2
    WORKER_MEM = 4096

    BASE_IP = "192.168.56.1"
    MASTER_IP = "#{BASE_IP}0"

    CLUSTER_NAME = "k3s"

    config.vm.define "#{CLUSTER_NAME}-master" do |master|
        master.vm.hostname = "#{CLUSTER_NAME}-master"
        master.vm.network "private_network", ip: MASTER_IP
        master.vm.provider "virtualbox" do |vb|
            vb.cpus = MASTER_CPUS
            vb.memory = MASTER_MEM
        end
        master.vm.provision "shell", path: "#{CLUSTER_NAME}-master.sh", args: [MASTER_IP]
        
        master.trigger.after :up do |trigger|
            trigger.info = "Create user and kubeconfig"
            trigger.run = {
                inline: <<-SHELL
                    bash -c "
                        if [ -d './.userconfig' ]; then
                            echo 'Kube Config already configured!'
                            exit 0
                        else
                            echo 'Configuring user....'
                            ./create-user.sh #{MASTER_IP} #{CLUSTER_NAME}
                        fi
                    "
                SHELL
            }
        end

        master.trigger.before :destroy do |trigger|
            trigger.info = "Remove cluster from kubeconfig and clean .userconfig"
            trigger.run = {inline: "bash ./cleanup.sh"}
        end
    end

    (1..2).each do |i|
        config.vm.define "#{CLUSTER_NAME}-worker#{i}" do |worker|
            worker.vm.hostname = "#{CLUSTER_NAME}-worker#{i}"
            worker.vm.network "private_network", ip: "#{BASE_IP}#{i}"
            worker.vm.provider "virtualbox" do |vb|
                vb.cpus = WORKER_CPUS
                vb.memory = WORKER_MEM
            end
            worker.vm.provision "shell", path: "#{CLUSTER_NAME}-worker.sh", args: [MASTER_IP]
        end
    end
end
