apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer
  labels:
    app: kafka-consumer
  namespace: apis-hmg
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: kafka-consumer
  type: ClusterIP