apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ts
  namespace: apps
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: app-ts
  template:
    metadata:
      labels:
        app: app-ts
    spec:
      containers:
        - name: app-ts
          image: mhrocha1997/api-template-nest:v10
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 400m
              memory: 128Mi
            limits:
              cpu: 700m
              memory: 256Mi
          envFrom:
            - configMapRef:
                name: app-ts-configmap
            - secretRef:
                name: app-ts-secrets
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
            periodSeconds: 10
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
            periodSeconds: 15
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: healthz
              port: 3000
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 1
            periodSeconds: 10
            initialDelaySeconds: 10
          # env:
          #   - name: APP
          #     valueFrom:
          #       configMapKeyRef:
          #         key: APP
          #         name: app-ts-configmap
          #   - name: API_KEY
          #     valueFrom:
          #       secretKeyRef:
          #         name: app-ts-secrets
          #         key: api-key
